// Central source of truth for Comply-Quick's legal copy ([Up10] Legal
// safeguards). Kept dependency-free so it can be imported from both server and
// client components (the generation wizard, the public Terms page, generated
// report exports, and the legal-review tooling all read from here).

/**
 * Mandatory disclaimer that must appear on every piece of generated content
 * (compliance packages, exported reports, public score pages). Wording is
 * fixed by the build plan — do not paraphrase per-surface.
 */
export const REPORT_DISCLAIMER = "This package is informational only. Consult a legal professional before deployment.";

/**
 * Longer-form disclaimer for UI surfaces that have room for it. Complements,
 * but never replaces, REPORT_DISCLAIMER.
 */
export const DISCLAIMER_LONG =
  "Comply-Quick provides automated operational templates based on technical configuration inputs. " +
  "Comply-Quick is not a law firm, does not provide formal legal counsel, and the outputs generated do not constitute legal advice.";

/**
 * Liability cap clause surfaced in the Terms of Service. Client assumes all
 * legal risk arising from use of generated content.
 */
export const LIABILITY_CAP =
  "We are not liable for damages from use of generated content. Client assumes all legal risk.";

/** Terms version + effective date. Bump when the terms materially change. */
export const TERMS_VERSION = "2026-07-03";
export const TERMS_EFFECTIVE_DATE = "July 3, 2026";

export interface TermsSection {
  heading: string;
  body: string[];
}

/**
 * Terms of Service content, rendered by /legal/terms. The liability-cap section
 * embeds LIABILITY_CAP verbatim so the page and any contractual reference stay
 * in sync.
 */
export const TERMS_OF_SERVICE: TermsSection[] = [
  {
    heading: "1. Nature of the Service",
    body: [
      "Comply-Quick generates automated compliance templates, privacy policies, and operational checklists from the technical and jurisdictional inputs you provide.",
      "Comply-Quick is not a law firm and does not provide legal advice. All generated content is informational only and must be reviewed by a qualified legal professional before you rely on or deploy it.",
    ],
  },
  {
    heading: "2. No Attorney–Client Relationship",
    body: [
      "Using Comply-Quick does not create an attorney–client relationship. No communication with Comply-Quick or its systems is privileged or confidential in the legal sense.",
    ],
  },
  {
    heading: "3. Limitation of Liability",
    body: [
      LIABILITY_CAP,
      "To the maximum extent permitted by law, Comply-Quick's total aggregate liability for any claim arising out of or related to the service is limited to the amount you paid to Comply-Quick in the twelve (12) months preceding the event giving rise to the claim.",
      "Comply-Quick is not liable for any indirect, incidental, consequential, special, or punitive damages, including lost profits, regulatory fines, or legal costs, arising from your use of generated content.",
    ],
  },
  {
    heading: "4. Client Responsibilities",
    body: [
      "You are responsible for the accuracy of the inputs you provide and for validating that generated content is appropriate for your specific circumstances, jurisdiction, and industry.",
      "You assume all legal and regulatory risk associated with deploying or distributing any content generated by the service.",
    ],
  },
  {
    heading: "5. Quality & Review",
    body: [
      "Comply-Quick's clause templates undergo periodic professional review. Review status is tracked internally, but a review does not constitute a legal guarantee for your specific use case.",
    ],
  },
];
