-- Comply-Quick — Calendar + Alerts (Phase 9 / [Up7]).
--
-- A single compliance calendar that unifies the deadlines a customer must not
-- miss. It has one owned, writable table — `compliance_tasks` — plus the
-- calendar *service* which merges these rows with events derived on the fly
-- from existing features (subscription renewals, weekly scan schedules from
-- `scan_monitors`, risk alerts from `compliance_alerts`, and regulation-change
-- notifications from Autopilot). Only the manual/auto tasks need persistence;
-- everything else is projected from its source of truth so it never drifts.
--
-- Agency integration: a task may optionally be scoped to an `agency_client`, so
-- an agency owner can plan per-client work and view a client's calendar. The
-- row is still owned by the agency owner (`user_id`), so RLS stays simple.
--
-- Numbered 0013 to sit after the partner program (0012).

create table if not exists public.compliance_tasks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  -- Optional: scope the task to one of the owner's agency clients.
  agency_client_id uuid references public.agency_clients (id) on delete cascade,
  title text not null,
  description text not null default '',
  -- What kind of deadline this is (drives the icon/colour + grouping in the UI).
  category text not null default 'task'
    check (category in ('task', 'renewal', 'scan', 'risk', 'regulation')),
  severity text not null default 'info'
    check (severity in ('info', 'warning', 'critical')),
  due_date date not null,
  status text not null default 'pending'
    check (status in ('pending', 'done', 'dismissed')),
  -- 'manual' = user-created; 'auto' = generated by a feature (e.g. Autopilot).
  source text not null default 'manual'
    check (source in ('manual', 'auto')),
  -- Optional back-references + free-form context for auto-generated tasks.
  related_scan_id uuid references public.scans (id) on delete set null,
  related_alert_id uuid references public.compliance_alerts (id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists compliance_tasks_user_due_idx
  on public.compliance_tasks (user_id, due_date);
create index if not exists compliance_tasks_client_due_idx
  on public.compliance_tasks (agency_client_id, due_date);

-- An auto-generated task should be created at most once per source event. This
-- partial unique index lets the generator upsert idempotently on a stable key
-- (e.g. "scan_due:<monitorId>:<period>") stored in metadata->>'dedupe_key'.
create unique index if not exists compliance_tasks_dedupe_idx
  on public.compliance_tasks (user_id, (metadata ->> 'dedupe_key'))
  where source = 'auto' and metadata ? 'dedupe_key';

-- ─── Row Level Security ──────────────────────────────────────────────────────
alter table public.compliance_tasks enable row level security;

drop policy if exists "compliance_tasks_select_own" on public.compliance_tasks;
create policy "compliance_tasks_select_own"
  on public.compliance_tasks for select
  using (auth.uid() = user_id);

drop policy if exists "compliance_tasks_insert_own" on public.compliance_tasks;
create policy "compliance_tasks_insert_own"
  on public.compliance_tasks for insert
  with check (auth.uid() = user_id);

drop policy if exists "compliance_tasks_update_own" on public.compliance_tasks;
create policy "compliance_tasks_update_own"
  on public.compliance_tasks for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "compliance_tasks_delete_own" on public.compliance_tasks;
create policy "compliance_tasks_delete_own"
  on public.compliance_tasks for delete
  using (auth.uid() = user_id);
